<div class="container">
    <div class="row-fluid">
        <form method="post" action="">
            <div class="form-group">
                <select name="categoria" class="form-control" required>
                    <option value="" selected>Selecione a Categoria</option>
                    <?php foreach($this->view->categoria as $categoria): ?>
                        <option value="<?= $categoria->getId() ?>"><?= $categoria->getNome() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Titulo do Post" maxlength="100" name="titulo" required />
            </div>
            <div class="form-group">
                <label for="exampleTextarea">Conteúdo do Post</label>
                <textarea class="form-control" rows="3" name="conteudo" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>