<div class="container">
    <div class="row-fluid">
        <form method="post" action="">
            <div class="form-group">
                <input type="text" class="form-control" value="<?= $this->view->produto->getNome() ?>" placeholder="Nome do Produto" maxlength="100" name="nome">
            </div>
            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
    </div>
</div>