<div class="container">
    <div class="row-fluid">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->view->categoria as $categoria): ?>
                <tr>
                    <th><?= $categoria->getId() ?></th>
                    <td><?= $categoria->getNome() ?></td>
                    <td>
                        <a href="editar-categoria?id=<?= $categoria->getId() ?>">Editar</a> |
                        <a href="remover-categoria?id=<?= $categoria->getId() ?>">Remover</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>